apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}
  namespace: {{ .Values.service2.namespace }}
  labels:
    app: {{ .Values.service2.name  }}
    qovery.com/service-id: {{ .Values.serviceId }}
spec:
  selector:
    app: {{ .Values.service2.name }}
    qovery.com/service-id: {{ .Values.serviceId }}
  ports:
  - protocol: TCP
    port: {{ .Values.service2.port }}
    targetPort: {{ .Values.service2.port }}
