apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service1.name }}
  labels:
    app: {{ .Values.service1.name  }}
    qovery.com/service-id: {{ .Values.serviceId }}
spec:
  selector:
    app: {{ .Values.service1.name }}
    qovery.com/service-id: {{ .Values.serviceId }}
  ports:
  - protocol: TCP
    port: {{ .Values.service1.port }}
    targetPort: {{ .Values.service1.port }}
