apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service1.name }}
  labels:
    app: {{ .Values.service1.name  }}
    qovery.com/service-id: {{ .Values.serviceId }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service1.name }}
      qovery.com/service-id: {{ .Values.serviceId }}
  template:
    metadata:
      labels:
        app: {{ .Values.service1.name }}
        qovery.com/service-id: {{ .Values.serviceId }}
    spec:
      containers:
      - name: {{ .Values.service1.name }}
        image: nginx:latest
        ports:
        - containerPort: {{ .Values.service1.port }}


